[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/item/:uid"
  to = "/?page=:page"
  status = 200
  query = {page = ":page" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

